/*
 * Automatically Generated by:
 * Arjuna Stub Generator Version 5.5.3 - $Date: 1996/09/10 15:38:44 $
 *
 * Do Not Edit By Hand
 *
 */

#ifdef STUB
#  pragma @NoRename
#endif

#include <StubGen/ClientRpc.h>

#include "LockMan_stub.h"

RemoteLockManager::RemoteLockManager ( const ClientRpcManager& manager, const RpcBuffer& phv ): RemoteStateManager(manager, RpcBuffer(phv,53946306)), _clientManager(manager), _myHashVal(phv)
{
_myHashVal << 53946306 << -1;
}

RemoteLockManager::~RemoteLockManager ( )
{
}

const TypeName RemoteLockManager::type ( ) const 
{
RpcBuffer _rvBuffer_;
RpcBuffer _callBuffer_(_myHashVal);
RpcBuffer _replyBuffer_;
RPC_Status _rpcStatus_ = OPER_UNKNOWN;
Int32 _serverStatus_ = OPER_INVOKED_OK;

TypeName _returnedValue_ = 0;

_rpcStatus_ = _clientManager.call(186814694, _callBuffer_, _serverStatus_, _replyBuffer_);
if (_rpcStatus_ == OPER_DONE)
{
switch(_serverStatus_)
{
case OPER_INVOKED_OK:
_replyBuffer_ >> _rvBuffer_;
_rvBuffer_ >> _returnedValue_;
break;
default:
_clientManager.rpcAbort(_rpcStatus_, _serverStatus_);
}
}
else
_clientManager.rpcAbort(_rpcStatus_, _serverStatus_);

return (_returnedValue_);
}
