/*
 * Automatically Generated by:
 * Arjuna Stub Generator Version 5.5.3 - $Date: 1997/09/25 15:31:02 $
 *
 * Do Not Edit By Hand
 *
 */

#ifdef STUB
#  pragma @NoRename
#endif

#include "Error_stub.h"

#include <StubGen/RpcBuffer.h>

RpcBuffer& operator<< ( RpcBuffer& rpcbuff, const Error& topack)
{
	rpcbuff << 5020002;
	topack.marshall(rpcbuff);
	return rpcbuff;
}


RpcBuffer& operator>> ( RpcBuffer& rpcbuff, Error& tounpack)
{
	Int32 hashVal;
	rpcbuff >> hashVal;
	if (hashVal != 5020002)
		rpcbuff.setState(BUFFER_BAD);
	else
		tounpack.unmarshall(rpcbuff);
	return rpcbuff;
}


RpcBuffer& operator<< ( RpcBuffer& rpcbuff, const Error *classptr )
{
if (rpcbuff.shouldPack(classptr))
rpcbuff << *classptr;
return rpcbuff;
}


RpcBuffer& operator>> ( RpcBuffer& rpcbuff, Error *& classptr )
{
const void *p = 0;
Int32 index = 0;
if (rpcbuff.unpackPtr(p, index))
{
if (classptr == 0)
classptr = new Error();
rpcbuff >> *classptr;
rpcbuff.saveUnpackedPtr(classptr,index);
}
else
{
if (p == 0)
delete classptr;
classptr = (Error *)p;
}return rpcbuff;
}


void Error::marshall ( RpcBuffer& rpcBuff ) const
{
rpcBuff << errCode;
rpcBuff << errorFacility;
rpcBuff << errorLevel;
rpcBuff << errorHead;
rpcBuff << errorText;
rpcBuff << nextError;

}


void Error::unmarshall ( RpcBuffer& rpcBuff )
{
rpcBuff >> errCode;
rpcBuff >> errorFacility;
rpcBuff >> errorLevel;
rpcBuff >> errorHead;
rpcBuff >> errorText;
rpcBuff >> nextError;

}

