/*
 * Automatically Generated by:
 * Arjuna Stub Generator Version 5.5.3 - $Date: 1997/09/25 15:31:02 $
 *
 * Do Not Edit By Hand
 *
 */

#ifdef STUB
#  pragma @NoRename
#endif

#ifndef FACCODE_STUB_H_
#define FACCODE_STUB_H_

#ifndef STUBGEN_TYPES_H_
#  include <StubGen/Types.h>
#endif

class RpcBuffer;
class ClientRpcManager;

/* @AutoMarshall */ 
enum FacilityCode {FAC_BASIC_RPC= 0x0001, FAC_ATOMIC_ACTION= 0x0002, FAC_CONCURRENCY_CONTROL= 0x0004, FAC_BUFFER_MAN= 0x0008, FAC_ABSTRACT_REC= 0x0010, FAC_OBJECT_STORE= 0x0020, FAC_STATE_MAN= 0x0040, FAC_ACTION_RPC= 0x0080, FAC_SHMEM= 0x0100, FAC_GENERAL= 0x0200, FAC_CRASH_RECOVERY= 0x0400, FAC_NAMING_AND_BINDING= 0x0800, FAC_REPLICATION= 0x1000, FAC_OBJECT_CLUSTERING= 0x2000, FAC_USER1= 0x4000, FAC_USER2= 0x8000, FAC_ALL= 0xffff};

#ifndef STUB
extern RpcBuffer& operator<< ( RpcBuffer&, FacilityCode* );
extern RpcBuffer& operator>> ( RpcBuffer&, FacilityCode& );
extern RpcBuffer& operator>> ( RpcBuffer&, FacilityCode*&);
#endif

#endif  /* FACCODE_STUB_H_ */
