/*
 * Automatically Generated by:
 * Arjuna Stub Generator Version 6.0.0 - $Date: 1997/06/09 19:52:22 $
 *
 * Do Not Edit By Hand
 *
 */

#ifdef STUB
#  pragma @NoRename
#endif

#include "BufferCheck_stub.h"
int main ( int argc, char **argv )
{
ServerBufferCheck oneBufferCheckServer;

oneBufferCheckServer.serve(argc, argv);
return 0;
}
