/*
 * Copyright (C) 1996, 1997, 1998,
 *
 * Department of Computing Science,
 * University of Newcastle upon Tyne,
 * Newcastle upon Tyne,
 * UK.
 *
 * $Id: CosPersistencePDS.idl,v 1.2 1998/11/12 09:00:23 nmcl Exp $
 */

#ifndef COSPERSISTENCEPDS_IDL_
#define COSPERSISTENCEPDS_IDL_

#pragma prefix "omg.org"

#include <idl/CosPersistencePID.idl>

module CosPersistencePDS
{
    interface PDS
    {
	CosPersistencePDS::PDS connect(in Object obj, in CosPersistencePID::PID p);
	void disconnect (in Object obj, in CosPersistencePID::PID p);
	void store (in Object obj, in CosPersistencePID::PID p);
	void restore (in Object obj, in CosPersistencePID::PID p);
	void deleteState (in Object obj, in CosPersistencePID::PID p);	    
    };
};

#endif
