/*
 * Copyright (C) 1996, 1997, 1998,
 *
 * Department of Computing Science,
 * University of Newcastle upon Tyne,
 * Newcastle upon Tyne,
 * UK.
 *
 * $Id: CosTSPortability.idl,v 1.2 1998/11/12 09:00:24 nmcl Exp $
 */

#ifndef COSTSPORTABILITY_IDL_
#define COSTSPORTABILITY_IDL_

#pragma prefix "omg.org"

#ifndef DRAFT3
#  include <idl/CosTSInteroperation.idl>
#else
#  include <idl/CosTransactions.idl>
#endif

module CosTSPostability  // PIDL
{
    typedef long ReqId;

    interface Sender
    {
#ifndef DRAFT3	
	void sending_request (in ReqId id, out CosTSInteroperation::PropagationContext ctx);
	void received_reply (in ReqId id, in CosTSInteroperation::PropagationContext ctx,
			     in CORBA::Environment env);
#else
	void sending_request (in ReqId id, out CosTransactions::PropagationContext ctx);
	void received_reply (in ReqId id, in CosTransactions::PropagationContext ctx,
			     in CORBA::Environment env);
#endif	
    };

    interface Receiver
    {
#ifndef DRAFT3	
	void received_request (in ReqId id, in CosTSInteroperation::PropagationContext ctx);
	void sending_reply (in ReqId id, out CosTSInteroperation::PropagationContext ctx);
#else
	void received_request (in ReqId id, in CosTransactions::PropagationContext ctx);
	void sending_reply (in ReqId id, out CosTransactions::PropagationContext ctx);
#endif
    };
	
};

#endif

