// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1999
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1999
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1.3
// License: non-commercial

package TestModule;

//
// IDL:/TestModule/Hammer:1.0
//
public class _HammerImplBase_tie extends _HammerImplBase
{
    private HammerOperations delegate_;

    public
    _HammerImplBase_tie(HammerOperations op)
    {
        delegate_ = op;
    }

    public HammerOperations
    _delegate()
    {
        return delegate_;
    }

    public void
    _delegate(HammerOperations op)
    {
        delegate_ = op;
    }

    //
    // IDL:/TestModule/Hammer/incr:1.0
    //
    public boolean
    incr(int _ob_a0,
         org.omg.CosTransactions.Control _ob_a1)
    {
        return delegate_.incr(_ob_a0,
                              _ob_a1);
    }

    //
    // IDL:/TestModule/Hammer/set:1.0
    //
    public boolean
    set(int _ob_a0,
        org.omg.CosTransactions.Control _ob_a1)
    {
        return delegate_.set(_ob_a0,
                             _ob_a1);
    }

    //
    // IDL:/TestModule/Hammer/get:1.0
    //
    public boolean
    get(org.omg.CORBA.IntHolder _ob_ah0,
        org.omg.CosTransactions.Control _ob_a1)
    {
        return delegate_.get(_ob_ah0,
                             _ob_a1);
    }
}
