// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1999
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1999
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1.3
// License: non-commercial

package TestModule;

//
// IDL:/TestModule/tranobject:1.0
//
public class _tranobjectImplBase_tie extends _tranobjectImplBase
{
    private tranobjectOperations delegate_;

    public
    _tranobjectImplBase_tie(tranobjectOperations op)
    {
        delegate_ = op;
    }

    public tranobjectOperations
    _delegate()
    {
        return delegate_;
    }

    public void
    _delegate(tranobjectOperations op)
    {
        delegate_ = op;
    }

    //
    // IDL:/TestModule/tranobject/foobar:1.0
    //
    public void
    foobar()
    {
        delegate_.foobar();
    }

    //
    // IDL:omg.org/CosTransactions/Resource/prepare:1.0
    //
    public org.omg.CosTransactions.Vote
    prepare()
        throws org.omg.CosTransactions.HeuristicMixed,
               org.omg.CosTransactions.HeuristicHazard
    {
        return delegate_.prepare();
    }

    //
    // IDL:omg.org/CosTransactions/Resource/rollback:1.0
    //
    public void
    rollback()
        throws org.omg.CosTransactions.HeuristicCommit,
               org.omg.CosTransactions.HeuristicMixed,
               org.omg.CosTransactions.HeuristicHazard
    {
        delegate_.rollback();
    }

    //
    // IDL:omg.org/CosTransactions/Resource/commit:1.0
    //
    public void
    commit()
        throws org.omg.CosTransactions.NotPrepared,
               org.omg.CosTransactions.HeuristicRollback,
               org.omg.CosTransactions.HeuristicMixed,
               org.omg.CosTransactions.HeuristicHazard
    {
        delegate_.commit();
    }

    //
    // IDL:omg.org/CosTransactions/Resource/commit_one_phase:1.0
    //
    public void
    commit_one_phase()
        throws org.omg.CosTransactions.HeuristicHazard
    {
        delegate_.commit_one_phase();
    }

    //
    // IDL:omg.org/CosTransactions/Resource/forget:1.0
    //
    public void
    forget()
    {
        delegate_.forget();
    }
}
