// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1999
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1999
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1.3
// License: non-commercial

package TestModule;

//
// IDL:/TestModule/grid:1.0
//
public interface grid extends org.omg.CosTransactions.Resource
{

    //
    // IDL:/TestModule/grid/height:1.0
    //
    public int
    height();

    //
    // IDL:/TestModule/grid/width:1.0
    //
    public int
    width();

    //
    // IDL:/TestModule/grid/set:1.0
    //
    public void
    set(int n,
        int m,
        int value,
        org.omg.CosTransactions.Control tran);

    //
    // IDL:/TestModule/grid/get:1.0
    //
    public int
    get(int n,
        int m,
        org.omg.CosTransactions.Control tran);
}
