//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosTransactions;

public class _ControlStub
    extends org.omg.CORBA.portable.ObjectImpl
    implements Control
{
    final public static java.lang.Class _opsClass = ControlOperations.class;


    public _ControlStub () {}

    public org.omg.CosTransactions.Terminator get_terminator() throws org.omg.CosTransactions.Unavailable
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                org.omg.CosTransactions.Terminator _result;
                try {
                    _output = _request("get_terminator", true);
                    _input = _invoke(_output);
                    _result = org.omg.CosTransactions.TerminatorHelper.read(_input);
                    return _result;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                        if (_exception_id.equals(org.omg.CosTransactions.UnavailableHelper.id())) {
                            throw org.omg.CosTransactions.UnavailableHelper.read(_exception.getInputStream());
                        }
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("get_terminator", _opsClass);
                if (_so == null) {
                    continue;
                }
                ControlOperations _self = (ControlOperations)_so.servant;
                try {
                    return _self.get_terminator();
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public org.omg.CosTransactions.Coordinator get_coordinator() throws org.omg.CosTransactions.Unavailable
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                org.omg.CosTransactions.Coordinator _result;
                try {
                    _output = _request("get_coordinator", true);
                    _input = _invoke(_output);
                    _result = org.omg.CosTransactions.CoordinatorHelper.read(_input);
                    return _result;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                        if (_exception_id.equals(org.omg.CosTransactions.UnavailableHelper.id())) {
                            throw org.omg.CosTransactions.UnavailableHelper.read(_exception.getInputStream());
                        }
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("get_coordinator", _opsClass);
                if (_so == null) {
                    continue;
                }
                ControlOperations _self = (ControlOperations)_so.servant;
                try {
                    return _self.get_coordinator();
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public static final String _interfaces[] =
    {"IDL:omg.org/CosTransactions/Control:1.0"};

    public String[] _ids()
    {
        return _interfaces;
    }

}
