//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosTransactions;

public class _SynchronizationStub
    extends org.omg.CORBA.portable.ObjectImpl
    implements Synchronization, org.omg.CosTransactions.TransactionalObject
{
    final public static java.lang.Class _opsClass = SynchronizationOperations.class;


    public _SynchronizationStub () {}

    public void before_completion()
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                try {
                    _output = _request("before_completion", true);
                    _input = _invoke(_output);
                    return;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("before_completion", _opsClass);
                if (_so == null) {
                    continue;
                }
                SynchronizationOperations _self = (SynchronizationOperations)_so.servant;
                try {
                    _self.before_completion();
                    return;
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public void after_completion(
        org.omg.CosTransactions.Status s
    )
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                try {
                    _output = _request("after_completion", true);
                    org.omg.CosTransactions.StatusHelper.write(_output, s);
                    _input = _invoke(_output);
                    return;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("after_completion", _opsClass);
                if (_so == null) {
                    continue;
                }
                SynchronizationOperations _self = (SynchronizationOperations)_so.servant;
                try {
                    _self.after_completion(s);
                    return;
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public static final String _interfaces[] =
    {"IDL:omg.org/CosTransactions/TransactionalObject:1.0", "IDL:omg.org/CosTransactions/Synchronization:1.0"};

    public String[] _ids()
    {
        return _interfaces;
    }

}
