//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosTransactions;

public interface ControlOperations

{
     org.omg.CosTransactions.Terminator get_terminator() throws org.omg.CosTransactions.Unavailable;

     org.omg.CosTransactions.Coordinator get_coordinator() throws org.omg.CosTransactions.Unavailable;

}
