//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosTransactions;
public final class Inactive
    extends org.omg.CORBA.UserException
{

    public Inactive() {
        super(InactiveHelper.id());
    }
}
