//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosTransactions;
public final class NoTransaction
    extends org.omg.CORBA.UserException
{

    public NoTransaction() {
        super(NoTransactionHelper.id());
    }
}
