//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//
// This Helper file provides several static methods needed to
// manipulate the IDL type

package org.omg.CosTransactions;

public class PropagationContextHelper
{
    public static void insert(
        org.omg.CORBA.Any any,
        org.omg.CosTransactions.PropagationContext value
    )
    {
        any.type(type());
        org.omg.CORBA.portable.OutputStream _stream = any.create_output_stream();
        write(_stream, value);
    }

    public static org.omg.CosTransactions.PropagationContext extract(
        org.omg.CORBA.Any any
    )
    {
        if (!any.type().equal(type()))
        {
            throw new org.omg.CORBA.BAD_TYPECODE("Error inserting/extracting value from typecode.");
        }
        else
        {
            return read(any.create_input_stream());
        }
    }

    private static org.omg.CORBA.TypeCode _type;
    public static org.omg.CORBA.TypeCode type()
    {
        if (_type == null)
        {
            org.omg.CORBA.StructMember[] _s = new org.omg.CORBA.StructMember[4];
            org.omg.CORBA.TypeCode _tc_timeout_0 = _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_ulong);
            _s[0] = new org.omg.CORBA.StructMember("timeout", _tc_timeout_0, null);
            org.omg.CORBA.TypeCode _tc_currentTransaction_0 = org.omg.CosTransactions.TransIdentityHelper.type();
            _s[1] = new org.omg.CORBA.StructMember("currentTransaction", _tc_currentTransaction_0, null);
            org.omg.CORBA.TypeCode _tc_parents_0 = org.omg.CosTransactions.PropagationContextPackage.parentsHelper.type();
            _s[2] = new org.omg.CORBA.StructMember("parents", _tc_parents_0, null);
            org.omg.CORBA.TypeCode _tc_implementation_specific_data_0 = _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_any);
            _s[3] = new org.omg.CORBA.StructMember("implementation_specific_data", _tc_implementation_specific_data_0, null);
            _type = _orb().create_struct_tc(id(),"PropagationContext",_s);
        }
        return _type;
    }

    public static org.omg.CORBA.ORB _orb()
    {
        return org.omg.CORBA.ORB.init();
    }

    public static String id()
    {
        return "IDL:omg.org/CosTransactions/PropagationContext:1.0";
    }

    public static org.omg.CosTransactions.PropagationContext read(
        org.omg.CORBA.portable.InputStream _stream
    )
    {
        org.omg.CosTransactions.PropagationContext value = new org.omg.CosTransactions.PropagationContext();
        value.timeout = _stream.read_ulong();
        value.currentTransaction = org.omg.CosTransactions.TransIdentityHelper.read(_stream);
        value.parents = org.omg.CosTransactions.PropagationContextPackage.parentsHelper.read(_stream);
        value.implementation_specific_data = _stream.read_any();

        return value;
    }

    public static void write(
        org.omg.CORBA.portable.OutputStream _stream,
        org.omg.CosTransactions.PropagationContext value
    )
    {
        _stream.write_ulong(value.timeout);
        org.omg.CosTransactions.TransIdentityHelper.write(_stream, value.currentTransaction);
        org.omg.CosTransactions.PropagationContextPackage.parentsHelper.write(_stream, value.parents);
        _stream.write_any(value.implementation_specific_data);
    }

}
