//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosTransactions;


public final class PropagationContext
    implements org.omg.CORBA.portable.IDLEntity
{
    public int timeout;
    public org.omg.CosTransactions.TransIdentity currentTransaction;
    public org.omg.CosTransactions.TransIdentity[] parents;
    public org.omg.CORBA.Any implementation_specific_data;

    public PropagationContext() {}
    public PropagationContext(
        int timeout,
        org.omg.CosTransactions.TransIdentity currentTransaction,
        org.omg.CosTransactions.TransIdentity[] parents,
        org.omg.CORBA.Any implementation_specific_data
    )
    {
        this.timeout = timeout;
        this.currentTransaction = currentTransaction;
        this.parents = parents;
        this.implementation_specific_data = implementation_specific_data;
    }
}
