//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosTransactions;
public class Status
    implements org.omg.CORBA.portable.IDLEntity
{
    public static final int _StatusActive = 0;
    public static final Status StatusActive = new Status(0);
    public static final int _StatusMarkedRollback = 1;
    public static final Status StatusMarkedRollback = new Status(1);
    public static final int _StatusPrepared = 2;
    public static final Status StatusPrepared = new Status(2);
    public static final int _StatusCommitted = 3;
    public static final Status StatusCommitted = new Status(3);
    public static final int _StatusRolledBack = 4;
    public static final Status StatusRolledBack = new Status(4);
    public static final int _StatusUnknown = 5;
    public static final Status StatusUnknown = new Status(5);
    public static final int _StatusPreparing = 6;
    public static final Status StatusPreparing = new Status(6);
    public static final int _StatusCommitting = 7;
    public static final Status StatusCommitting = new Status(7);
    public static final int _StatusRollingBack = 8;
    public static final Status StatusRollingBack = new Status(8);
    public static final int _StatusNoTransaction = 9;
    public static final Status StatusNoTransaction = new Status(9);

    public static final Status IT_ENUM_MAX = new Status(Integer.MAX_VALUE);

    public static Status from_int(
        int value
    )
    {
        switch (value)
        {
            case _StatusActive: return StatusActive;

            case _StatusMarkedRollback: return StatusMarkedRollback;

            case _StatusPrepared: return StatusPrepared;

            case _StatusCommitted: return StatusCommitted;

            case _StatusRolledBack: return StatusRolledBack;

            case _StatusUnknown: return StatusUnknown;

            case _StatusPreparing: return StatusPreparing;

            case _StatusCommitting: return StatusCommitting;

            case _StatusRollingBack: return StatusRollingBack;

            case _StatusNoTransaction: return StatusNoTransaction;

            default:
                 return IT_ENUM_MAX;
        }
    }

    private int ___value;

    public int value()
    {
        return ___value;
    }

    private Status(
        int value
    )
    {
        ___value = value;
    }

    public java.lang.Object clone()
    {
        return from_int(___value);
    }
}
