//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosTransactions;

public interface SubtransactionAwareResourceOperations
extends 
    org.omg.CosTransactions.ResourceOperations
{
     void commit_subtransaction(
        org.omg.CosTransactions.Coordinator parent
    );

     void rollback_subtransaction();

}
