//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosTransactions;

public interface TerminatorOperations

{
     void commit(
        boolean report_heuristics
    ) throws org.omg.CosTransactions.HeuristicMixed, org.omg.CosTransactions.HeuristicHazard;

     void rollback();

}
