//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//
// This Helper file provides several static methods needed to
// manipulate the IDL type

package org.omg.CosTransactions;

public class TransIdentityHelper
{
    public static void insert(
        org.omg.CORBA.Any any,
        org.omg.CosTransactions.TransIdentity value
    )
    {
        any.type(type());
        org.omg.CORBA.portable.OutputStream _stream = any.create_output_stream();
        write(_stream, value);
    }

    public static org.omg.CosTransactions.TransIdentity extract(
        org.omg.CORBA.Any any
    )
    {
        if (!any.type().equal(type()))
        {
            throw new org.omg.CORBA.BAD_TYPECODE("Error inserting/extracting value from typecode.");
        }
        else
        {
            return read(any.create_input_stream());
        }
    }

    private static org.omg.CORBA.TypeCode _type;
    public static org.omg.CORBA.TypeCode type()
    {
        if (_type == null)
        {
            org.omg.CORBA.StructMember[] _s = new org.omg.CORBA.StructMember[3];
            org.omg.CORBA.TypeCode _tc_coord_0 = org.omg.CosTransactions.CoordinatorHelper.type();
            _s[0] = new org.omg.CORBA.StructMember("coord", _tc_coord_0, null);
            org.omg.CORBA.TypeCode _tc_term_0 = org.omg.CosTransactions.TerminatorHelper.type();
            _s[1] = new org.omg.CORBA.StructMember("term", _tc_term_0, null);
            org.omg.CORBA.TypeCode _tc_otid_0 = org.omg.CosTransactions.otid_tHelper.type();
            _s[2] = new org.omg.CORBA.StructMember("otid", _tc_otid_0, null);
            _type = _orb().create_struct_tc(id(),"TransIdentity",_s);
        }
        return _type;
    }

    public static org.omg.CORBA.ORB _orb()
    {
        return org.omg.CORBA.ORB.init();
    }

    public static String id()
    {
        return "IDL:omg.org/CosTransactions/TransIdentity:1.0";
    }

    public static org.omg.CosTransactions.TransIdentity read(
        org.omg.CORBA.portable.InputStream _stream
    )
    {
        org.omg.CosTransactions.TransIdentity value = new org.omg.CosTransactions.TransIdentity();
        value.coord = org.omg.CosTransactions.CoordinatorHelper.read(_stream);
        value.term = org.omg.CosTransactions.TerminatorHelper.read(_stream);
        value.otid = org.omg.CosTransactions.otid_tHelper.read(_stream);

        return value;
    }

    public static void write(
        org.omg.CORBA.portable.OutputStream _stream,
        org.omg.CosTransactions.TransIdentity value
    )
    {
        org.omg.CosTransactions.CoordinatorHelper.write(_stream, value.coord);
        org.omg.CosTransactions.TerminatorHelper.write(_stream, value.term);
        org.omg.CosTransactions.otid_tHelper.write(_stream, value.otid);
    }

}
