//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosTransactions;

public interface TransactionFactoryOperations

{
     org.omg.CosTransactions.Control create(
        int time_out
    );

     org.omg.CosTransactions.Control recreate(
        org.omg.CosTransactions.PropagationContext ctx
    );

}
