//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosTransactions;
public final class Unavailable
    extends org.omg.CORBA.UserException
{

    public Unavailable() {
        super(UnavailableHelper.id());
    }
}
