//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosTransactions;
public final class WrongTransaction
    extends org.omg.CORBA.UserException
{

    public WrongTransaction() {
        super(WrongTransactionHelper.id());
    }
}
