#!/bin/sh

#
# Copyright (C) 1993
# 
# Department of Computing Science,
# The University,
# Newcastle upon Tyne,
# UK.
#
# $Id: run,v 1.5 1993/08/09 12:26:44 nmcl Exp $
#

./Test1 -rec -num 10
./Test2 -rec -iter 5
