/*
 * Automatically Generated by:
 * Arjuna Stub Generator Version 5.5.3 - $Date: 1996/09/10 15:38:44 $
 *
 * Do Not Edit By Hand
 *
 */

#ifdef STUB
#  pragma @NoRename
#endif

#ifndef STUB
#include <StubGen/RpcBuffer.h>
#include <StubGen/ClientRpcMan.h>


#ifndef NEWSTUDENTRECORDNUMBER_SERVER
#undef NewStudentRecordNumber
#define NewStudentRecordNumber RemoteNewStudentRecordNumber
#endif

class RemoteNewStudentRecordNumber: public RemoteLockManager
{
public:
	RemoteNewStudentRecordNumber ( SOutCome& , int , ClientRpcManager *_cRpcMan_ = ClientRpcManager::createInstance("NewStudentRecordNumberServer",1));
	RemoteNewStudentRecordNumber ( SOutCome& , const Uid& , ClientRpcManager *_cRpcMan_ = ClientRpcManager::createInstance("NewStudentRecordNumberServer",1));
	~RemoteNewStudentRecordNumber ( );
	void setNumber ( SOutCome& , int );
	void getNumber ( SOutCome& , int& );
	void getThenIncreaseNumber ( SOutCome& , int& );
	virtual Boolean hasRemoteState ( ) const ;
	virtual Boolean useStoreLocation ( ) const ;
	virtual Boolean save_state ( ObjectState& , ObjectType );
	virtual Boolean restore_state ( ObjectState& , ObjectType );
	virtual const TypeName type ( ) const ;
protected:
	RemoteNewStudentRecordNumber(const ClientRpcManager&, const RpcBuffer&);
private:
	ClientRpcManager _clientManager;
	RpcBuffer _myHashVal;
}
;


#ifdef NEWSTUDENTRECORDNUMBER_SERVER
#undef NewStudentRecordNumber
#define NewStudentRecordNumber LocalNewStudentRecordNumber
#endif

class LocalNewStudentRecordNumber;

class ServerNewStudentRecordNumber: public ServerLockManager
{

public:
	ServerNewStudentRecordNumber ();
	~ServerNewStudentRecordNumber ();

	void serve (int, char **);
	Int32 dispatchToClass (LocalNewStudentRecordNumber*, Int32, RpcBuffer&, RpcBuffer&);

private:
	Int32 dispatchToOper (LocalNewStudentRecordNumber *,Int32, RpcBuffer&, RpcBuffer&);

	Int32 NewStudentRecordNumber197604361(LocalNewStudentRecordNumber *, RpcBuffer&, RpcBuffer&);
	Int32 NewStudentRecordNumber69029060(LocalNewStudentRecordNumber *, RpcBuffer&, RpcBuffer&);
	Int32 NewStudentRecordNumber235758822(LocalNewStudentRecordNumber *, RpcBuffer&, RpcBuffer&);
	Int32 setNumber28897865(LocalNewStudentRecordNumber *, RpcBuffer&, RpcBuffer&);
	Int32 getNumber193966489(LocalNewStudentRecordNumber *, RpcBuffer&, RpcBuffer&);
	Int32 getThenIncreaseNumber125127561(LocalNewStudentRecordNumber *, RpcBuffer&, RpcBuffer&);
	Int32 hasRemoteState169145798(LocalNewStudentRecordNumber *, RpcBuffer&, RpcBuffer&);
	Int32 useStoreLocation26673606(LocalNewStudentRecordNumber *, RpcBuffer&, RpcBuffer&);
	Int32 save_state142033461(LocalNewStudentRecordNumber *, RpcBuffer&, RpcBuffer&);
	Int32 restore_state200938517(LocalNewStudentRecordNumber *, RpcBuffer&, RpcBuffer&);
	Int32 type267827174(LocalNewStudentRecordNumber *, RpcBuffer&, RpcBuffer&);

	LocalNewStudentRecordNumber *theRealObject;
	RpcBuffer _constructArgs_;
	Int32 _constructOpcode_;
	Int32 _constructRefCount_;
	RpcBuffer _constructResult_;
};
#endif


#ifdef STUB
#  define LocalNewStudentRecordNumber NewStudentRecordNumber
#endif

/* @Remote, @NoMarshall */ class LocalNewStudentRecordNumber: public LocalLockManager
{
public:
	/* @NoMarshall */ LocalNewStudentRecordNumber ( SOutCome& , int );
	/* @NoMarshall */ LocalNewStudentRecordNumber ( SOutCome& , const Uid& );
	/* @NoMarshall */ ~LocalNewStudentRecordNumber ( );
	/* @NoMarshall */ void setNumber ( SOutCome& , int );
	/* @NoMarshall */ void getNumber ( SOutCome& , int& );
	/* @NoMarshall */ void getThenIncreaseNumber ( SOutCome& , int& );
	/* @NoMarshall */ virtual Boolean hasRemoteState ( ) const ;
	/* @NoMarshall */ virtual Boolean useStoreLocation ( ) const ;
	/* @NoMarshall */ virtual Boolean save_state ( ObjectState& , ObjectType );
	/* @NoMarshall */ virtual Boolean restore_state ( ObjectState& , ObjectType );
	/* @NoMarshall */ virtual const TypeName type ( ) const ;
private:
	int _number;
};

