/*
 * Automatically Generated by:
 * Arjuna Stub Generator Version 5.5.3 - $Date: 1996/09/10 15:38:44 $
 *
 * Do Not Edit By Hand
 *
 */

#ifdef STUB
#  pragma @NoRename
#endif

#ifndef STUDENTRECORD_STUB_H_
#define STUDENTRECORD_STUB_H_

#ifndef STUBGEN_TYPES_H_
#  include <StubGen/Types.h>
#endif

class RpcBuffer;
class ClientRpcManager;


#include <Common/Boolean.h>

#include <Common/Buffer_stub.h>

#include <Common/Uid_stub.h>

#include <Arjuna/LockMan_stub.h>

#include "SOutCome_stub.h"
#include "StudentRecord_stubclass.h"

#endif  /* STUDENTRECORD_STUB_H_ */
