/*
 * Copyright (C) 1997, 1998, 1999, 2000, 2001,
 *
 * Arjuna Solutions Limited,
 * Newcastle upon Tyne,
 * Tyne and Wear,
 * UK.
 *
 * $Id: CosPersistencePDS.idl,v 1.1.42.1 2001/03/20 16:24:47 nmcl Exp $
 */

#ifndef COSPERSISTENCEPDS_IDL_
#define COSPERSISTENCEPDS_IDL_

#pragma prefix "omg.org"

#include <idl/CosPersistencePID.idl>

module CosPersistencePDS
{
    interface PDS
    {
	CosPersistencePDS::PDS connect(in Object obj, in CosPersistencePID::PID p);
	void disconnect (in Object obj, in CosPersistencePID::PID p);
	void store (in Object obj, in CosPersistencePID::PID p);
	void restore (in Object obj, in CosPersistencePID::PID p);
	void deleteState (in Object obj, in CosPersistencePID::PID p);	    
    };
};

#endif
