/*
 * Copyright (C) 1997,
 *
 * Department of Computing Science,
 * University of Newcastle upon Tyne,
 * Newcastle upon Tyne,
 * UK.
 *
 * $Id: SimpleRpcStubCodeGenerator.java,v 1.1 1997/08/05 14:23:12 nmcl Exp $
 */

package JavaStubGenerator.Arjuna.simplerpc;

import JavaStubGenerator.stub.StubCodeGenerator;
import JavaStubGenerator.stub.StubCodeObject;
import java.lang.Class;
import java.lang.reflect.Method;
import java.lang.reflect.Constructor;
import java.io.PrintWriter;
import java.io.FileOutputStream;

import java.io.IOException;
import java.lang.SecurityException;
import java.lang.ClassNotFoundException;
import java.lang.InstantiationException;
import java.lang.IllegalAccessException;

public class SimpleRpcStubCodeGenerator implements StubCodeGenerator
{

public SimpleRpcStubCodeGenerator ()
    {
	clientCode = new SimpleRpcClientStubCodeGenerator(this);
	serverCode = new SimpleRpcServerStubCodeGenerator(this);
    }
    
public boolean hasConstructors ()
    {
	return true;
    }

public boolean errorCheck (Class c)
    {
	return true;
    }
    
public void exceptionType (boolean uniform)
    {
	_uniformException = uniform;

	clientCode.exceptionType(uniform);
	serverCode.exceptionType(uniform);
    }
    
public void produceClientStubCode (String interfaceName, Method[] methods) throws IOException
    {
	clientCode.produceStubCode(interfaceName, methods);
    }    

public void produceServerStubCode (String interfaceName, Method[] methods) throws IOException
    {
	serverCode.produceStubCode(interfaceName, methods);
    }

public void produceClientStubCode (String interfaceName, Constructor[] constructors, Method[] methods) throws IOException
    {
	System.out.println("Warning - produceClientStubCode ignoring constructors.");

	produceClientStubCode(interfaceName, methods);
    }

public void produceServerStubCode (String interfaceName, Constructor[] constructor, Method[] methods) throws IOException
    {
	System.out.println("Warning - produceServerStubCode ignoring constructors.");

	produceServerStubCode(interfaceName, methods);
    }

public void printClass (String interfaceName, Constructor[] constructors,
			Method[] methods, PrintWriter out) throws IOException
    {
	out.println("class "+interfaceName);
	out.println("{");

	if (constructors.length > 0)
	{
	    for (int j = 0; j < constructors.length; j++)
		out.println(constructors[i]);
	}
	
	if (methods.length > 0)
	{
	    for (int i = 0; i < methods.length; i++)
		out.println(methods[i]);
	}

	out.println("}");

	out.flush();
    }

public void producePreamble (PrintWriter out) throws IOException
    {
	out.println("/*");
	out.println(" * Copyright (C) 1997,");
	out.println(" *");
	out.println(" * Department of Computing Science,");
	out.println(" * University of Newcastle upon Tyne,");
	out.println(" * Newcastle upon Tyne,");
	out.println(" * UK.");
	out.println(" *");
	out.println(" * $Id: SimpleRpcStubCodeGenerator.java,v 1.1 1997/08/05 14:23:12 nmcl Exp $");
	out.println(" */\n");
	
	out.println("// Automatically generated by ArjunaII Java Stub Compiler.");
	out.println("// WARNING: do not edit by hand.\n");

	out.flush();
    }

protected boolean _uniformException = false;
protected StubCodeObject clientCode = null;
protected StubCodeObject serverCode = null;
    
}
