[InstallShield Silent]
Version=v2.10.000
File=Response File
[Application]
Name=Arjuna
Version=3.4
Company=Arjuna Technologies
[DlgOrder]
Dlg0=Welcome-0
Count=5
Dlg1=AskDestPath-0
Dlg2=SetupType-0
Dlg3=SelectFolder-0
Dlg4=MessageBox-0
[Welcome-0]
Result=0
[AskDestPath-0]
szPath=C:\Arjuna\ArjunaPR3.4\
Result=1
[SetupType-0]
Result=301
szDir=C:\Arjuna\ArjunaPR3.4\
[SelectFolder-0]
szResultFolder=Sample App Group
Result=1
[MessageBox-0]
Result=1
