/*
 * Automatically Generated by:
 * Arjuna Stub Generator Version 5.5.3 - $Date: 1996/09/10 15:38:44 $
 *
 * Do Not Edit By Hand
 *
 */

#ifdef STUB
#  pragma @NoRename
#endif

#include "Lock_stub.h"

#include <StubGen/RpcBuffer.h>

RpcBuffer& operator<< ( RpcBuffer& rpcbuff, const Lock& topack)
{
	rpcbuff << 341403;
	topack.marshall(rpcbuff);
	return rpcbuff;
}


RpcBuffer& operator>> ( RpcBuffer& rpcbuff, Lock& tounpack)
{
	Int32 hashVal;
	rpcbuff >> hashVal;
	if (hashVal != 341403)
		rpcbuff.setState(BUFFER_BAD);
	else
		tounpack.unmarshall(rpcbuff);
	return rpcbuff;
}


RpcBuffer& operator<< ( RpcBuffer& rpcbuff, const Lock *classptr )
{
if (rpcbuff.shouldPack(classptr))
rpcbuff << *classptr;
return rpcbuff;
}


RpcBuffer& operator>> ( RpcBuffer& rpcbuff, Lock *& classptr )
{
const void *p = 0;
Int32 index = 0;
if (rpcbuff.unpackPtr(p, index))
{
if (classptr == 0)
classptr = new Lock();
rpcbuff >> *classptr;
rpcbuff.saveUnpackedPtr(classptr,index);
}
else
{
if (p == 0)
delete classptr;
classptr = (Lock *)p;
}return rpcbuff;
}

