#!/bin/sh

#
# Copyright (C) 1993
# 
# Department of Computing Science,
# The University,
# Newcastle upon Tyne,
# UK.
#
# $Id: run,v 1.1 1993/11/03 15:02:06 nmcl Exp $
#

./Test1 -rec -num 10
./Test2 -rec -iter 5
