#define PRODUCT_NAME "ArjunaTS"
#define VERSION "2"
#define MAJOR "2"
#define MINOR "0"
#define CANDIDATE_RELEASE "Beta"
#define RELEASE "internal"
#define MODULE "JTSArjuna"
#define SOURCEID "unknown"
#define BUILDINFO "Arjuna Solutions Ltd. [unknown]"
#define BUILDNUMBER "2_2_0"
#define DATE "Thu Sep 20 13:40:33 2001"
#define NOTES "none"
