#define PRODUCT_NAME "JTSArjuna"
#define VERSION "2"
#define MAJOR "0"
#define MINOR "0"
#define CANDIDATE_RELEASE "none"
#define RELEASE "internal"
#define MODULE "JTSArjuna"
#define SOURCEID "unknown"
#define BUILDINFO "Arjuna Solutions Ltd. [unknown]"
#define DATE "Tue Aug 1 17:11:51 BST 2000"
#define NOTES "none"
