//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosActivityAdministration;

public class _PropertyGroupAttributesStub
    extends org.omg.CORBA.portable.ObjectImpl
    implements PropertyGroupAttributes
{
    final public static java.lang.Class _opsClass = PropertyGroupAttributesOperations.class;


    public _PropertyGroupAttributesStub () {}

    public java.lang.String get_attribute(
        java.lang.String name
    ) throws org.omg.CosActivityAdministration.NoSuchAttribute
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                java.lang.String _result;
                try {
                    _output = _request("get_attribute", true);
                    _output.write_string(name);
                    _input = _invoke(_output);
                    _result = _input.read_string();
                    return _result;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                        if (_exception_id.equals(org.omg.CosActivityAdministration.NoSuchAttributeHelper.id())) {
                            throw org.omg.CosActivityAdministration.NoSuchAttributeHelper.read(_exception.getInputStream());
                        }
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("get_attribute", _opsClass);
                if (_so == null) {
                    continue;
                }
                PropertyGroupAttributesOperations _self = (PropertyGroupAttributesOperations)_so.servant;
                try {
                    return _self.get_attribute(name);
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public void set_attribute(
        java.lang.String name,
        java.lang.String value
    ) throws org.omg.CosActivityAdministration.AttributeAlreadyExists
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                try {
                    _output = _request("set_attribute", true);
                    _output.write_string(name);
                    _output.write_string(value);
                    _input = _invoke(_output);
                    return;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                        if (_exception_id.equals(org.omg.CosActivityAdministration.AttributeAlreadyExistsHelper.id())) {
                            throw org.omg.CosActivityAdministration.AttributeAlreadyExistsHelper.read(_exception.getInputStream());
                        }
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("set_attribute", _opsClass);
                if (_so == null) {
                    continue;
                }
                PropertyGroupAttributesOperations _self = (PropertyGroupAttributesOperations)_so.servant;
                try {
                    _self.set_attribute(name, value);
                    return;
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public void replace_attribute(
        java.lang.String name,
        java.lang.String value
    )
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                try {
                    _output = _request("replace_attribute", true);
                    _output.write_string(name);
                    _output.write_string(value);
                    _input = _invoke(_output);
                    return;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("replace_attribute", _opsClass);
                if (_so == null) {
                    continue;
                }
                PropertyGroupAttributesOperations _self = (PropertyGroupAttributesOperations)_so.servant;
                try {
                    _self.replace_attribute(name, value);
                    return;
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public static final String _interfaces[] =
    {"IDL:omg.org/CosActivityAdministration/PropertyGroupAttributes:1.0"};

    public String[] _ids()
    {
        return _interfaces;
    }

}
