//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosActivityAdministration;

public class _PropertyGroupManagerStub
    extends org.omg.CORBA.portable.ObjectImpl
    implements PropertyGroupManager
{
    final public static java.lang.Class _opsClass = PropertyGroupManagerOperations.class;


    public _PropertyGroupManagerStub () {}

    public org.omg.CosActivity.PropertyGroup create(
        org.omg.CosActivity.PropertyGroup parent,
        byte[] gid
    )
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                org.omg.CosActivity.PropertyGroup _result;
                try {
                    _output = _request("create", true);
                    org.omg.CosActivity.PropertyGroupHelper.write(_output, parent);
                    org.omg.CosActivity.GlobalIdHelper.write(_output, gid);
                    _input = _invoke(_output);
                    _result = org.omg.CosActivity.PropertyGroupHelper.read(_input);
                    return _result;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("create", _opsClass);
                if (_so == null) {
                    continue;
                }
                PropertyGroupManagerOperations _self = (PropertyGroupManagerOperations)_so.servant;
                try {
                    return _self.create(parent, gid);
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public org.omg.CosActivity.PropertyGroupIdentity marshal_request(
        org.omg.CosActivity.PropertyGroup pg
    )
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                org.omg.CosActivity.PropertyGroupIdentity _result;
                try {
                    _output = _request("marshal_request", true);
                    org.omg.CosActivity.PropertyGroupHelper.write(_output, pg);
                    _input = _invoke(_output);
                    _result = org.omg.CosActivity.PropertyGroupIdentityHelper.read(_input);
                    return _result;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("marshal_request", _opsClass);
                if (_so == null) {
                    continue;
                }
                PropertyGroupManagerOperations _self = (PropertyGroupManagerOperations)_so.servant;
                try {
                    return _self.marshal_request(pg);
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public org.omg.CosActivity.PropertyGroupIdentity marshal_response(
        org.omg.CosActivity.PropertyGroup pg
    )
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                org.omg.CosActivity.PropertyGroupIdentity _result;
                try {
                    _output = _request("marshal_response", true);
                    org.omg.CosActivity.PropertyGroupHelper.write(_output, pg);
                    _input = _invoke(_output);
                    _result = org.omg.CosActivity.PropertyGroupIdentityHelper.read(_input);
                    return _result;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("marshal_response", _opsClass);
                if (_so == null) {
                    continue;
                }
                PropertyGroupManagerOperations _self = (PropertyGroupManagerOperations)_so.servant;
                try {
                    return _self.marshal_response(pg);
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public org.omg.CosActivity.PropertyGroup unmarshal_request(
        org.omg.CosActivity.PropertyGroupIdentity mpg,
        org.omg.CosActivity.PropertyGroup pg,
        org.omg.CosActivity.PropertyGroup parent,
        byte[] gid
    )
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                org.omg.CosActivity.PropertyGroup _result;
                try {
                    _output = _request("unmarshal_request", true);
                    org.omg.CosActivity.PropertyGroupIdentityHelper.write(_output, mpg);
                    org.omg.CosActivity.PropertyGroupHelper.write(_output, pg);
                    org.omg.CosActivity.PropertyGroupHelper.write(_output, parent);
                    org.omg.CosActivity.GlobalIdHelper.write(_output, gid);
                    _input = _invoke(_output);
                    _result = org.omg.CosActivity.PropertyGroupHelper.read(_input);
                    return _result;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("unmarshal_request", _opsClass);
                if (_so == null) {
                    continue;
                }
                PropertyGroupManagerOperations _self = (PropertyGroupManagerOperations)_so.servant;
                try {
                    return _self.unmarshal_request(mpg, pg, parent, gid);
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public void unmarshal_response(
        org.omg.CosActivity.PropertyGroupIdentity mpg,
        org.omg.CosActivity.PropertyGroup pg
    )
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                try {
                    _output = _request("unmarshal_response", true);
                    org.omg.CosActivity.PropertyGroupIdentityHelper.write(_output, mpg);
                    org.omg.CosActivity.PropertyGroupHelper.write(_output, pg);
                    _input = _invoke(_output);
                    return;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("unmarshal_response", _opsClass);
                if (_so == null) {
                    continue;
                }
                PropertyGroupManagerOperations _self = (PropertyGroupManagerOperations)_so.servant;
                try {
                    _self.unmarshal_response(mpg, pg);
                    return;
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public void destroy() throws org.omg.CosActivity.AlreadyDestroyed
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                try {
                    _output = _request("destroy", true);
                    _input = _invoke(_output);
                    return;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                        if (_exception_id.equals(org.omg.CosActivity.AlreadyDestroyedHelper.id())) {
                            throw org.omg.CosActivity.AlreadyDestroyedHelper.read(_exception.getInputStream());
                        }
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("destroy", _opsClass);
                if (_so == null) {
                    continue;
                }
                PropertyGroupManagerOperations _self = (PropertyGroupManagerOperations)_so.servant;
                try {
                    _self.destroy();
                    return;
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public static final String _interfaces[] =
    {"IDL:omg.org/CosActivityAdministration/PropertyGroupManager:1.0"};

    public String[] _ids()
    {
        return _interfaces;
    }

}
