//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosActivityAdministration;
public final class AttributeAlreadyExists
    extends org.omg.CORBA.UserException
{

    public AttributeAlreadyExists() {
        super(AttributeAlreadyExistsHelper.id());
    }
}
