//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosActivityAdministration;

public interface Current
    extends CurrentOperations,
    org.omg.CosActivity.Current
{
}
