//
// Java code automatically generated by the JART IDL Compiler
// Do not edit this code!
//
// This Holder class is generated to allow support for out and inout
// parameter passing modes

package org.omg.CosActivityAdministration;
public final class NoSuchAttributeHolder
    implements org.omg.CORBA.portable.Streamable
{
    public org.omg.CosActivityAdministration.NoSuchAttribute value;

    public NoSuchAttributeHolder() {}

    public NoSuchAttributeHolder(
        org.omg.CosActivityAdministration.NoSuchAttribute value
    )
    {
        this.value = value;
    }

    public void _read(
        org.omg.CORBA.portable.InputStream _stream
    )
    {
        value = org.omg.CosActivityAdministration.NoSuchAttributeHelper.read(_stream);
    }

    public void _write(
        org.omg.CORBA.portable.OutputStream _stream
    )
    {
        org.omg.CosActivityAdministration.NoSuchAttributeHelper.write(_stream, value);
    }

    public org.omg.CORBA.TypeCode _type()
    {
        return org.omg.CosActivityAdministration.NoSuchAttributeHelper.type();
    }

}
