//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosActivityAdministration;

public interface PropertyGroupAttributesOperations

{
     java.lang.String get_attribute(
        java.lang.String name
    ) throws org.omg.CosActivityAdministration.NoSuchAttribute;

     void set_attribute(
        java.lang.String name,
        java.lang.String value
    ) throws org.omg.CosActivityAdministration.AttributeAlreadyExists;

     void replace_attribute(
        java.lang.String name,
        java.lang.String value
    );

}
