//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosActivityAdministration;
public final class PropertyGroupAlreadyRegistered
    extends org.omg.CORBA.UserException
{

    public PropertyGroupAlreadyRegistered() {
        super(PropertyGroupAlreadyRegisteredHelper.id());
    }
}
