//
// Java code automatically generated by the JART IDL Compiler
// Do not edit this code!
//
// This Holder class is generated to allow support for out and inout
// parameter passing modes

package org.omg.CosActivityAdministration;
public final class PropertyGroupNotRegisteredHolder
    implements org.omg.CORBA.portable.Streamable
{
    public org.omg.CosActivityAdministration.PropertyGroupNotRegistered value;

    public PropertyGroupNotRegisteredHolder() {}

    public PropertyGroupNotRegisteredHolder(
        org.omg.CosActivityAdministration.PropertyGroupNotRegistered value
    )
    {
        this.value = value;
    }

    public void _read(
        org.omg.CORBA.portable.InputStream _stream
    )
    {
        value = org.omg.CosActivityAdministration.PropertyGroupNotRegisteredHelper.read(_stream);
    }

    public void _write(
        org.omg.CORBA.portable.OutputStream _stream
    )
    {
        org.omg.CosActivityAdministration.PropertyGroupNotRegisteredHelper.write(_stream, value);
    }

    public org.omg.CORBA.TypeCode _type()
    {
        return org.omg.CosActivityAdministration.PropertyGroupNotRegisteredHelper.type();
    }

}
