//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package com.arjuna.CosRecovery.Admin;

public class _RecoveryManagerStub
    extends org.omg.CORBA.portable.ObjectImpl
    implements RecoveryManager
{
    final public static java.lang.Class _opsClass = RecoveryManagerOperations.class;


    public _RecoveryManagerStub () {}

    public java.lang.String createIOR(
        java.lang.String id
    )
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                java.lang.String _result;
                try {
                    _output = _request("createIOR", true);
                    _output.write_string(id);
                    _input = _invoke(_output);
                    _result = _input.read_string();
                    return _result;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("createIOR", _opsClass);
                if (_so == null) {
                    continue;
                }
                RecoveryManagerOperations _self = (RecoveryManagerOperations)_so.servant;
                try {
                    return _self.createIOR(id);
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public static final String _interfaces[] =
    {"IDL:CosRecovery.arjuna.com/Admin/RecoveryManager:1.0"};

    public String[] _ids()
    {
        return _interfaces;
    }

}
