/*
 * Copyright (C) 2000
 *
 * Arjuna Solutions Limited,
 * Newcastle upon Tyne,
 * Tyne and Wear,
 * UK.
 *
 * $Id: CosRecovery.tmpl,v 1.1.2.1.30.2 2001/03/19 15:59:26 nmcl Exp $
 */





#pragma prefix "CosRecovery.arjuna.com"




module Admin
{
    /*
     * WARNING: do not rely upon this interface being
     * available in subsequent releases!
     */

    interface RecoveryManager
    {
	string createIOR (in string id);
    };
    
    interface RecoveryManagerAdmin
    {
	long ping ();
    };
};

// COSRECOVERY_IDL_





