//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//
// This Helper file provides several static methods needed to
// manipulate the IDL type

package com.arjuna.CosRecovery.Admin;

public class RecoveryManagerAdminHelper
{
    public static void insert(
        org.omg.CORBA.Any any,
        com.arjuna.CosRecovery.Admin.RecoveryManagerAdmin value
    )
    {
        any.type(type());
        org.omg.CORBA.portable.OutputStream _stream = any.create_output_stream();
        write(_stream, value);
    }

    public static com.arjuna.CosRecovery.Admin.RecoveryManagerAdmin extract(
        org.omg.CORBA.Any any
    )
    {
        if (!any.type().equal(type()))
        {
            throw new org.omg.CORBA.BAD_TYPECODE("Error inserting/extracting value from typecode.");
        }
        else
        {
            return read(any.create_input_stream());
        }
    }

    private static org.omg.CORBA.TypeCode _type;
    public static org.omg.CORBA.TypeCode type()
    {
        if (_type == null)
        {
            _type = _orb().create_interface_tc(id(), "RecoveryManagerAdmin");
        }
        return _type;
    }

    public static org.omg.CORBA.ORB _orb()
    {
        return org.omg.CORBA.ORB.init();
    }

    public static String id()
    {
        return "IDL:CosRecovery.arjuna.com/Admin/RecoveryManagerAdmin:1.0";
    }

    public static com.arjuna.CosRecovery.Admin.RecoveryManagerAdmin read(
        org.omg.CORBA.portable.InputStream _stream
    )
    {
        return (narrow(_stream.read_Object()));
    }

    public static void write(
        org.omg.CORBA.portable.OutputStream _stream,
        com.arjuna.CosRecovery.Admin.RecoveryManagerAdmin value
    )
    {
        _stream.write_Object(value);
    }

    public static com.arjuna.CosRecovery.Admin.RecoveryManagerAdmin narrow(
        org.omg.CORBA.Object _obj
    ) throws org.omg.CORBA.BAD_PARAM
    {
        if (_obj == null)
        {
            return null;
        }
        if (_obj instanceof com.arjuna.CosRecovery.Admin.RecoveryManagerAdmin)
        {
            return (com.arjuna.CosRecovery.Admin.RecoveryManagerAdmin)_obj;
        }
        if (_obj._is_a(id()))
        {
            com.arjuna.CosRecovery.Admin._RecoveryManagerAdminStub _ref = new com.arjuna.CosRecovery.Admin._RecoveryManagerAdminStub();
            _ref._set_delegate(((org.omg.CORBA.portable.ObjectImpl)_obj)._get_delegate());
            return _ref;
        }
        else
        {
            throw new org.omg.CORBA.BAD_PARAM();
        }
    }

}
