//
// Java code automatically generated by the JART IDL Compiler
// Do not edit this code!
//
// This Holder class is generated to allow support for out and inout
// parameter passing modes

package com.arjuna.CosRecovery.Admin;
public final class RecoveryManagerHolder
    implements org.omg.CORBA.portable.Streamable
{
    public com.arjuna.CosRecovery.Admin.RecoveryManager value;

    public RecoveryManagerHolder() {}

    public RecoveryManagerHolder(
        com.arjuna.CosRecovery.Admin.RecoveryManager value
    )
    {
        this.value = value;
    }

    public void _read(
        org.omg.CORBA.portable.InputStream _stream
    )
    {
        value = com.arjuna.CosRecovery.Admin.RecoveryManagerHelper.read(_stream);
    }

    public void _write(
        org.omg.CORBA.portable.OutputStream _stream
    )
    {
        com.arjuna.CosRecovery.Admin.RecoveryManagerHelper.write(_stream, value);
    }

    public org.omg.CORBA.TypeCode _type()
    {
        return com.arjuna.CosRecovery.Admin.RecoveryManagerHelper.type();
    }

}
