/*
 * Copyright (C) 1996, 1997, 1998, 1999,
 *
 * Department of Computing Science,
 * The University,
 * Newcastle upon Tyne,
 * UK.
 *
 * $Id: OTS_Exceptions.h,v 1.1.4.1 1999/04/16 13:47:38 nmcl Exp $
 */

#ifndef COSTRANSACTIONS_OTS_EXCEPTIONS_H_
#define COSTRANSACTIONS_OTS_EXCEPTIONS_H_

/*
 * The Minor version numbers for some system exceptions
 * we may raise.
 */

#define OTS_GENERAL_BASE 20000
#define INACTIVE_TRANSACTION OTS_GENERAL_BASE+1

/*
 * UNKNOWN
 */

#define OTS_UNKNOWN_BASE 30000
#define UNKNOWN_EXCEPTION OTS_UNKNOWN_BASE+1
#define GETTIMEOUT_FAILED OTS_UNKNOWN_BASE+2
#define UNEXPECTED_SYSTEMEXCEPTION OTS_UNKNOWN_BASE+3
#define SYNCHRONIZATION_EXCEPTION OTS_UNKNOWN_BASE+4

/*
 * BAD_OPERATION
 */

#define OTS_BAD_OPERATION_BASE 40000
#define SERVERAA_COMMIT OTS_BAD_OPERATION_BASE+1
#define SERVERAA_PREPARE OTS_BAD_OPERATION_BASE+2
#define ATOMICACTION_COMMIT OTS_BAD_OPERATION_BASE+3
#define ATOMICACTION_ROLLBACK OTS_BAD_OPERATION_BASE+4
#define NO_TRANSACTION OTS_BAD_OPERATION_BASE+5

/*
 * TRANSACTION_ROLLEDBACK
 */

#define TRANSACTION_ROLLEDBACK_BASE 50000
#define FAILED_TO_COMMIT TRANSACTION_ROLLEDBACK_BASE+1
#define ALREADY_ROLLEDBACK TRANSACTION_ROLLEDBACK_BASE+2
#define MARKED_ROLLEDBACK TRANSACTION_ROLLEDBACK_BASE+3
#define FAILED_TO_PREPARE TRANSACTION_ROLLEDBACK_BASE+4

/*
 * INVALID_TRANSACTION
 */

#define INVALID_TRANSACTION_BASE 60000
#define ALREADY_TERMINATED INVALID_TRANSACTION_BASE+1
#define UNKNOWN_INVALID INVALID_TRANSACTION_BASE+2
#define ALREADY_BEGUN INVALID_TRANSACTION_BASE+3
#define ADD_FAILED INVALID_TRANSACTION_BASE+4
#define UNAVAILABLE_COORDINATOR INVALID_TRANSACTION_BASE+5
#define UNAVAILABLE_TRANSACTION INVALID_TRANSACTION_BASE+6

/*
 * WRONG_TRANSACTION
 */

#define WRONG_TRANSACTION_BASE 70000
#define NOT_CURRENT_TRANSACTION WRONG_TRANSACTION_BASE+1
#define SERVERAA_NO_CONTROL WRONG_TRANSACTION_BASE+2

/*
 * TRANSACTION_REQUIRED
 */

#define TRANSACTION_REQUIRED_BASE 80000
#define NO_TXCONTEXT TRANSACTION_REQUIRED_BASE+1

#endif
