/*
 * Copyright (C) 1993
 *
 * Department of Computing Science,
 * The University,
 * Newcastle upon Tyne,
 * UK.
 */

/*
 * $Id: ondeadline.h,v 1.1 1994/05/03 10:53:53 ngdp Exp $
 */

#ifndef RAJDOOT_ONDEADLINE_H_
#define RAJDOOT_ONDEADLINE_H_

/* include file for users of Rajdoot RPC Mechanism */

#ifndef SETJMP_H_
#  include <System/setjmp.h>
#endif

extern jmp_buf  _rpcenv; /* Stack environment variable */

/*
 * The following macro is to be invoked within the server code
 * before calling `getwork()'. It saves the stack environment so
 * that, if an ABORT signal generated by the expiration of the
 * deadline occurs, the server is re-initialised to `getwork()'.
 */

#define ONDEADLINE()     setjmp(_rpcenv);   

#endif
