#define MODULE "ArjunaCommon"
#define SOURCEID "unknown"
#define BUILDINFO "Arjuna Solutions Ltd. [unknown]"
#define VERSION "4.3.0"
#define DATE "Thu Sep 20 13:40:17 2001"
#define NOTES "none"
