#!/bin/sh

rm -rf res/out*

for i in 1 2 3 4 5 6 7
do
    echo regis$i
    for j in 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15
    do
         ./SimulationRun -host regis$i -port 5500 -user test$j$i -number 1000 -v < ./dataset 1> res/out$j$i 2>&1 &
         sleep 1
    done
done
