// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 1999
// Object-Oriented Concepts, Inc.
// Billerica, MA, USA
//
// Copyright (c) 1999
// Object-Oriented Concepts GmbH
// Ettlingen, Germany
//
// All Rights Reserved
//
// **********************************************************************

// Version: 3.1.3
// License: non-commercial

package TestModule;

//
// IDL:/TestModule/tranobject:1.0
//
public interface tranobject extends org.omg.CosTransactions.Resource
{

    //
    // IDL:/TestModule/tranobject/foobar:1.0
    //
    public void
    foobar();
}
