/*
 *  Do not edit by hand - automatically generated by configure.
 */

#ifndef ARJUNACONFIG_H_
#define ARJUNACONFIG_H_

#define NUMBER_SERVERS 1
#define MIN_SERVERS 1
#define staticKeyMap "/home/nmcl/Install/RegistrationInstall/mapfiles/keymap"
#define overflowKeyMap "/tmp/overflowmap"
#define overflowLockFile "/tmp/overflowmap.lock"
#define newKeyMap "/home/nmcl/Install/RegistrationInstall/mapfiles/newstudents"

#define ObjectStoreConfiguration "/home/nmcl/Install/RegistrationInstall/configurations/ObjectStore"
#define IndexConfigurationFile "/home/nmcl/Install/RegistrationInstall/configurations/Index"
#define ServerConfigurationFile "/home/nmcl/Install/RegistrationInstall/configurations/Server"

#define dumpingFile "/home/nmcl/Install/isDumping"
#define readonlyFile "/home/nmcl/Install/ReadOnly"

#endif
