#define LOGINACTION "Login"
#define LOGIN "LN"
#define LOGINSUCC "LS"
#define LOGINFAIL "LF"

#define NEWREC "NR"
#define NEWRECSUCC "NS"
#define NEWRECFAIL "NF"

#define OPENREC "OR"
#define OPENRECSUCC "OS"
#define OPENRECFAIL "OF"

#define CLOSEREC "CR"
#define CLOSERECSUCC "CS"
#define CLOSERECFAIL "CF"

#define SAVEREC "SR"
#define SAVESUCC "SS"
#define SAVEFAIL "SF"

#define DELETEREC "DR"
#define DELETESUCC "DS"
#define DELETEFAIL "DF"

#define FINDREC "FR"
#define FINDSUCC "FS"
#define FINDFAIL "FF"

#define READREC "RR"
#define READSUCC "RS"
#define READFAIL "RF"

#define VERSION "VN"
#define VERSIONSUCC "VS"
#define VERSIONFAIL "VF"

#define ACTIONFAULT "AF"
#define MESSAGE "MF"

/* Misc messages */
#define NOSAVEMESS "This is the test Student Information Server, changes are NOT passed to the Student Office."
#define SHUTDOWNMESS "Please note this service will be unavailable from 4:00pm for extraction of data."
#define USERLOCKFAIL "Failed to open the user lock file."
#define ALREADYLOGGEDIN "This user ident is currently in use."
#define ACCCIOLFAIL "An operation failed while trying to validate access."
#define ACCESSVIOLATION "This action violates your security clearance."
#define UNKOWNACCESSVIOLATION "This action violates your security clearance."
#define NOTYOUNG "The date of the message sent is invalid."
#define NOTYOUNG_FATAL "The date of your messages is intolerable."
#define ALREADYOPEN "You already have a record open."
#define NORECOPEN "You don't have a record open."
#define INVALIDSTUDNUMB "Your requests doesn't contain a valid student number."
#define ACTIONFAILURE "Operation failed please try again."
#define INVALIDNUMBER "Invalid student number."
#define SERVERFAILURE "A student record server failure has occurred. Please try again."
#define VIRTUALSERVERFAILURE "The database is overloaded for this student. Please try again."

/* Action fault messages */
#define FATAL "FATAL : "
#define VERSIONFAIL_AF "An error occur while checking version information."
#define OLDTOKEN_AF "Token too old error."
#define INCORRECTACTION "Version information was expected but not received."
#define OPENFILEFAIL "Failed to open the version information file."
#define DRIVERSOFFLINE "Drivers are currently off-line. Try again later."

/* Version fault messages */
#define UNKNOWNMACHTYPE "Machine type code not known."
#define OLDVERSION "There is a newer version of this software from http://naburn.ncl.ac.uk/"
#define OLDVERSION_FATAL "This software is too old. Get a new version from http://naburn.ncl.ac.uk/"

/* Registration command verification messages */
#define NOENOUGHCHARS "Insufficient characters to be a valid command."
#define CMDNOTKNOWN "Command not known."
#define NODEFYET "This function is not defined yet."

/* OpenRec command messages */
#define OR_FAILOPENINDEX "Failed to open the index database."
#define OR_ALREADYLOCKED "Another user has the record locked. Please try again later"
#define OR_RECNOTFOUND "The requested record cannot be found."
#define OR_GETLOCKFAILED "Getting the lock on the record failed."
#define OR_OPENDATAFAILED "Failed to open the database file."
#define OR_FAILEDTOLOCATE "Unable to locate record within datafile."
#define OR_OPENRECFAULT "There has been a general open record fault."
#define OR_DATALOCKFAIL "Failed to lock the datafile."
#define OR_INDEXLOCKFAIL "Failed to lock the index file."
#define OR_ENTRYDELETED "Entry has been marked deleted."
#define OR_GENERALFAULT "A unknown error has occured."
#define OR_EMPTYRECORD "Record is empty. Possible error during new."
#define OR_HOSTFAILURE "Failed to contact student record machine. Please exit and try again."
#define OR_SERVERFAILURE "Insufficient server machines available."
#define OR_SERVERACTIVE "Attempt to start server with one already active."
#define OR_ISDUMPING "The system is temporarily unavailable for data extraction"

/* SaveRec command messages */
#define SR_INDEXLOCKFAIL "Failed to lock the index database."
#define SR_INDEXOPENFAIL "Failed to open the index database."
#define SR_RECNOTFOUND "Failed to find record in index."
#define SR_NOTLOCKOWNER "You are not the record lock owner."
#define SR_DATALOCKFAIL "Failed to lock the database file."
#define SR_OPENDATAFAIL "Failed to open the database file."
#define SR_FAILEDTOLOCATE "Unable to locate record within datafile."
#define SR_WRITEFAIL "Failed to write the full record to database."
#define SR_INDEXMODFAIL "Failed to modify the index."
#define SR_GENERALFAULT "An unknown fault has occured."
#define SR_NORECOPEN "You don't have this record open."
#define SR_INVALIDDATA "Store data invalid."
#define SR_READONLY "Sorry, no modifications are allowed. The system is in read-only mode."

/* CloseRec command messages */
#define CR_INDEXLOCKFAIL "Failed to lock the index database."
#define CR_INDEXOPENFAIL "Failed to open the index database."
#define CR_RECNOTFOUND "Failed to find record in index."
#define CR_NOTLOCKOWNER "You are not the record lock owner."
#define CR_LOCKCHANGEFAIL "Failed to change index information."
#define CR_GENERALERROR "An unknown error has occured."

/* NewRec command messages */
#define NR_INDEXLOCKFAIL "Failed to lock the index database."
#define NR_INDEXOPENFAIL "Failed to open the index database."
#define NR_BASEFINDFAIL "Failed to find the base record."
#define NR_BASESTORFAIL "Failed to store the updated base record."
#define NR_NEWRECFOUND "The new record was already in the database."
#define NR_DATALOCKFAIL "Failed to lock the database."
#define NR_DATAOPENFAIL "Failed to open the data file"
#define NR_DATASEEKFAIL "Failed to seek in the data file"
#define NR_FAILWHILWRIT "Fail during write record"
#define NR_GENERALFAIL "General fault occured"
#define NR_POOLEXHAUSTED "New student number pool exhausted."
#define NR_HOSTFAILURE "Failed to contact student record machine. Please exit and try again."
#define NR_SERVERFAILURE "Insufficient server machines available."
#define NR_SERVERACTIVE "Attempt to start server with one already active."
#define NR_ATOMICINTERROR "Failed to get and increment index value."
#define NR_INDEXACTIONFAILURE "Atomic index action commit failure."
#define NR_INVALIDNUMBER "Invalid student number."
#define NR_ISDUMPING "The system is temporarily unavailable for data extraction"
#define NR_RECORDEXISTS "A student record already exists with that number."
#define NR_NONEWMAP "Failed to find newkeymap database."

/* ReadRec command messages */
#define RR_FAILOPENINDEX "Failed to open the index database."
#define RR_ALREADYLOCKED "Another user has the record locked. Please try again later."
#define RR_RECNOTFOUND "The requests record cannot be found."
#define RR_GETLOCKFAILED "Getting the lock on the record failed."
#define RR_OPENDATAFAILED "Failed to open the database file."
#define RR_FAILEDTOLOCATE "Unable to locate record within datafile."
#define RR_OPENRECFAULT "There has been a general open record fault."

/* FindRec command messages */
#define FR_FINDBAR "Find requests are currently blocked."
#define FR_TMPOPENFAIL "Failed to open the temp datafile."
#define FR_TMPSEEKFAIL "Failed to re-initialise the temp file."
#define FR_TMPMAKEFAIL "Failed to make the tempfile."
#define FR_NOTMPFILE "Incorrect action - no more entries in temp file."
#define FR_TMPREADFAIL "Failed to read from the temp file."
#define FR_NODETAILS "*** No details can be found ***"
#define FR_NORECORDS "There are no records matching request."
#define FR_SURMATCHFAIL "There are no surnames matching."
#define FR_SURDBOPENFAIL "Unable to open the surname database."
#define FR_SURPOSFAIL "Failed to set position within surname file."
#define FR_SURREADFAIL "Failed to read from the surname file."
#define FR_TMPWRITEFAIL "Write to temp file failed."
#define FR_TMPGETPOSFAIL "Failed to get temp file position."

/* DeleteRec command messages */
#define DR_INDEXLOCKFAIL "Failed to lock the index database."
#define DR_DBOPENFAIL "Failed to open the index database."
#define DR_NORECORD "Record not found."
#define DR_NOTLOCKOWN "You are not the owner of the record lock."
#define DR_DBWRITEFAIL "Failed to update the database."
#define DR_GENERAL "An unknown error has occured."

