/*
 * Automatically Generated by:
 * Arjuna Stub Generator Version 5.5.3 - $Date: 1996/09/10 15:38:44 $
 *
 * Do Not Edit By Hand
 *
 */

#ifdef STUB
#  pragma @NoRename
#endif

#include "LockDaemonIf_stub.h"
int main ( int argc, char **argv )
{
ServerLockDaemonIf oneLockDaemonIfServer;

oneLockDaemonIfServer.serve(argc, argv);
return 0;
}
