//
// Java generated by the OrbixWeb IDL compiler 
//

package org.omg.CosTransactions.PropagationContextPackage;

import IE.Iona.OrbixWeb._OrbixWeb;


public final class parentsHolder
     implements org.omg.CORBA.portable.Streamable
{
    public org.omg.CosTransactions.TransIdentity[] value;

    public parentsHolder() {}

    public parentsHolder(org.omg.CosTransactions.TransIdentity[] value) {
        this.value = value;
    }
    public void _read (org.omg.CORBA.portable.InputStream _stream)
    {
        value = org.omg.CosTransactions.PropagationContextPackage.parentsHelper.read(_stream);
    }
    public void _write (org.omg.CORBA.portable.OutputStream _stream)
    {
        org.omg.CosTransactions.PropagationContextPackage.parentsHelper.write(_stream, value);
    }
    public org.omg.CORBA.TypeCode _type ()
    {
        return parentsHelper.type();
    }
}
