//
// Java generated by the OrbixWeb IDL compiler 
//

package org.omg.CosTransactions.otid_tPackage;

import IE.Iona.OrbixWeb._OrbixWeb;


public final class tidHolder
     implements org.omg.CORBA.portable.Streamable
{
    public byte[] value;

    public tidHolder() {}

    public tidHolder(byte[] value) {
        this.value = value;
    }
    public void _read (org.omg.CORBA.portable.InputStream _stream)
    {
        value = org.omg.CosTransactions.otid_tPackage.tidHelper.read(_stream);
    }
    public void _write (org.omg.CORBA.portable.OutputStream _stream)
    {
        org.omg.CosTransactions.otid_tPackage.tidHelper.write(_stream, value);
    }
    public org.omg.CORBA.TypeCode _type ()
    {
        return tidHelper.type();
    }
}
