//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package com.arjuna.ArjunaOTS;

public interface CurrentOperations
extends 
    org.omg.CosTransactions.CurrentOperations
{
     int get_timeout();

}
