//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package com.arjuna.ArjunaOTS;
public final class Destroyed
    extends org.omg.CORBA.UserException
{

    public Destroyed() {
        super(DestroyedHelper.id());
    }
}
