//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package com.arjuna.ArjunaOTS;

public interface OTSAbstractRecord
    extends OTSAbstractRecordOperations,
    com.arjuna.ArjunaOTS.ArjunaSubtranAwareResource
{
}
