//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//
// This Helper file provides several static methods needed to
// manipulate the IDL type

package com.arjuna.ArjunaOTS;

public class TransactionInfoHelper
{
    public static void insert(
        org.omg.CORBA.Any any,
        com.arjuna.ArjunaOTS.TransactionInfo value
    )
    {
        any.type(type());
        org.omg.CORBA.portable.OutputStream _stream = any.create_output_stream();
        write(_stream, value);
    }

    public static com.arjuna.ArjunaOTS.TransactionInfo extract(
        org.omg.CORBA.Any any
    )
    {
        if (!any.type().equal(type()))
        {
            throw new org.omg.CORBA.BAD_TYPECODE("Error inserting/extracting value from typecode.");
        }
        else
        {
            return read(any.create_input_stream());
        }
    }

    private static org.omg.CORBA.TypeCode _type;
    public static org.omg.CORBA.TypeCode type()
    {
        if (_type == null)
        {
            org.omg.CORBA.StructMember[] _s = new org.omg.CORBA.StructMember[3];
            org.omg.CORBA.TypeCode _tc_currentDepth_0 = _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_long);
            _s[0] = new org.omg.CORBA.StructMember("currentDepth", _tc_currentDepth_0, null);
            org.omg.CORBA.TypeCode _tc_timeout_0 = _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_long);
            _s[1] = new org.omg.CORBA.StructMember("timeout", _tc_timeout_0, null);
            org.omg.CORBA.TypeCode _tc_numberOfThreads_0 = _orb().get_primitive_tc(org.omg.CORBA.TCKind.tk_long);
            _s[2] = new org.omg.CORBA.StructMember("numberOfThreads", _tc_numberOfThreads_0, null);
            _type = _orb().create_struct_tc(id(),"TransactionInfo",_s);
        }
        return _type;
    }

    public static org.omg.CORBA.ORB _orb()
    {
        return org.omg.CORBA.ORB.init();
    }

    public static String id()
    {
        return "IDL:arjuna.com/ArjunaOTS/TransactionInfo:1.0";
    }

    public static com.arjuna.ArjunaOTS.TransactionInfo read(
        org.omg.CORBA.portable.InputStream _stream
    )
    {
        com.arjuna.ArjunaOTS.TransactionInfo value = new com.arjuna.ArjunaOTS.TransactionInfo();
        value.currentDepth = _stream.read_long();
        value.timeout = _stream.read_long();
        value.numberOfThreads = _stream.read_long();

        return value;
    }

    public static void write(
        org.omg.CORBA.portable.OutputStream _stream,
        com.arjuna.ArjunaOTS.TransactionInfo value
    )
    {
        _stream.write_long(value.currentDepth);
        _stream.write_long(value.timeout);
        _stream.write_long(value.numberOfThreads);
    }

}
