//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package com.arjuna.ArjunaOTS;

public interface UidCoordinatorOperations
extends 
    org.omg.CosTransactions.CoordinatorOperations
{
     java.lang.String uid();

     java.lang.String topLevelUid();

}
