//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosActivity;

public class _ActivityTokenStub
    extends org.omg.CORBA.portable.ObjectImpl
    implements ActivityToken
{
    final public static java.lang.Class _opsClass = ActivityTokenOperations.class;


    public _ActivityTokenStub () {}

    public org.omg.CosActivity.ActivityContext get_context()
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                org.omg.CosActivity.ActivityContext _result;
                try {
                    _output = _request("get_context", true);
                    _input = _invoke(_output);
                    _result = org.omg.CosActivity.ActivityContextHelper.read(_input);
                    return _result;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("get_context", _opsClass);
                if (_so == null) {
                    continue;
                }
                ActivityTokenOperations _self = (ActivityTokenOperations)_so.servant;
                try {
                    return _self.get_context();
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public void destroy() throws org.omg.CosActivity.AlreadyDestroyed
    {
        while (true) {
            if(!_is_local()) {
                org.omg.CORBA.portable.OutputStream _output = null;
                org.omg.CORBA.portable.InputStream _input = null;
                try {
                    _output = _request("destroy", true);
                    _input = _invoke(_output);
                    return;
                }
                catch (org.omg.CORBA.portable.RemarshalException _exception) {
                    continue;
                }
                catch (org.omg.CORBA.portable.ApplicationException _exception)
                {
                    final java.lang.String _exception_id = _exception.getId();
                        if (_exception_id.equals(org.omg.CosActivity.AlreadyDestroyedHelper.id())) {
                            throw org.omg.CosActivity.AlreadyDestroyedHelper.read(_exception.getInputStream());
                        }
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception;" + _exception_id);
                }
                finally {
                    _releaseReply(_input);
                }
            }
            else {
                org.omg.CORBA.portable.ServantObject _so = _servant_preinvoke("destroy", _opsClass);
                if (_so == null) {
                    continue;
                }
                ActivityTokenOperations _self = (ActivityTokenOperations)_so.servant;
                try {
                    _self.destroy();
                    return;
                }
                finally {
                    _servant_postinvoke(_so);
                }
            }
        }
    }


    public static final String _interfaces[] =
    {"IDL:omg.org/CosActivity/ActivityToken:1.0"};

    public String[] _ids()
    {
        return _interfaces;
    }

}
