//
// Java code automatically generated by the JART IDL Compiler
// Do not edit this code!
//
// This Holder class is generated to allow support for out and inout
// parameter passing modes

package org.omg.CosActivity;
public final class ActionHolder
    implements org.omg.CORBA.portable.Streamable
{
    public org.omg.CosActivity.Action value;

    public ActionHolder() {}

    public ActionHolder(
        org.omg.CosActivity.Action value
    )
    {
        this.value = value;
    }

    public void _read(
        org.omg.CORBA.portable.InputStream _stream
    )
    {
        value = org.omg.CosActivity.ActionHelper.read(_stream);
    }

    public void _write(
        org.omg.CORBA.portable.OutputStream _stream
    )
    {
        org.omg.CosActivity.ActionHelper.write(_stream, value);
    }

    public org.omg.CORBA.TypeCode _type()
    {
        return org.omg.CosActivity.ActionHelper.type();
    }

}
