//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosActivity;


public final class ActivityContext
    implements org.omg.CORBA.portable.IDLEntity
{
    public org.omg.CosActivity.ActivityIdentity[] hierarchy;
    public org.omg.CORBA.Any invocation_specific_data;

    public ActivityContext() {}
    public ActivityContext(
        org.omg.CosActivity.ActivityIdentity[] hierarchy,
        org.omg.CORBA.Any invocation_specific_data
    )
    {
        this.hierarchy = hierarchy;
        this.invocation_specific_data = invocation_specific_data;
    }
}
