//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosActivity;


public final class ActivityIdentity
    implements org.omg.CORBA.portable.IDLEntity
{
    public int type;
    public int timeout;
    public org.omg.CosActivity.ActivityCoordinator coord;
    public byte[] ctxId;
    public org.omg.CosActivity.PropertyGroupIdentity[] pgCtx;
    public org.omg.CORBA.Any activity_specific_data;

    public ActivityIdentity() {}
    public ActivityIdentity(
        int type,
        int timeout,
        org.omg.CosActivity.ActivityCoordinator coord,
        byte[] ctxId,
        org.omg.CosActivity.PropertyGroupIdentity[] pgCtx,
        org.omg.CORBA.Any activity_specific_data
    )
    {
        this.type = type;
        this.timeout = timeout;
        this.coord = coord;
        this.ctxId = ctxId;
        this.pgCtx = pgCtx;
        this.activity_specific_data = activity_specific_data;
    }
}
