//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosActivity;
public final class InvalidState
    extends org.omg.CORBA.UserException
{

    public InvalidState() {
        super(InvalidStateHelper.id());
    }
}
