//
// Java code automatically generated by the JART IDL Compiler
// Do not edit this code!
//
// This Holder class is generated to allow support for out and inout
// parameter passing modes

package org.omg.CosActivity;
public final class InvalidParentContextHolder
    implements org.omg.CORBA.portable.Streamable
{
    public org.omg.CosActivity.InvalidParentContext value;

    public InvalidParentContextHolder() {}

    public InvalidParentContextHolder(
        org.omg.CosActivity.InvalidParentContext value
    )
    {
        this.value = value;
    }

    public void _read(
        org.omg.CORBA.portable.InputStream _stream
    )
    {
        value = org.omg.CosActivity.InvalidParentContextHelper.read(_stream);
    }

    public void _write(
        org.omg.CORBA.portable.OutputStream _stream
    )
    {
        org.omg.CosActivity.InvalidParentContextHelper.write(_stream, value);
    }

    public org.omg.CORBA.TypeCode _type()
    {
        return org.omg.CosActivity.InvalidParentContextHelper.type();
    }

}
