//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosActivity;


public final class Outcome
    implements org.omg.CORBA.portable.IDLEntity
{
    public java.lang.String outcome_name;
    public org.omg.CORBA.Any application_specific_data;

    public Outcome() {}
    public Outcome(
        java.lang.String outcome_name,
        org.omg.CORBA.Any application_specific_data
    )
    {
        this.outcome_name = outcome_name;
        this.application_specific_data = application_specific_data;
    }
}
