//
// Java code automatically generated by the JART IDL Compiler
// Do not edit this code!
//
// This Holder class is generated to allow support for out and inout
// parameter passing modes

package org.omg.CosActivity;
public final class PropertyGroupIdentityHolder
    implements org.omg.CORBA.portable.Streamable
{
    public org.omg.CosActivity.PropertyGroupIdentity value;

    public PropertyGroupIdentityHolder() {}

    public PropertyGroupIdentityHolder(
        org.omg.CosActivity.PropertyGroupIdentity value
    )
    {
        this.value = value;
    }

    public void _read(
        org.omg.CORBA.portable.InputStream _stream
    )
    {
        value = org.omg.CosActivity.PropertyGroupIdentityHelper.read(_stream);
    }

    public void _write(
        org.omg.CORBA.portable.OutputStream _stream
    )
    {
        org.omg.CosActivity.PropertyGroupIdentityHelper.write(_stream, value);
    }

    public org.omg.CORBA.TypeCode _type()
    {
        return org.omg.CosActivity.PropertyGroupIdentityHelper.type();
    }

}
