//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosActivity;
public final class PropertyGroupUnknown
    extends org.omg.CORBA.UserException
{

    public PropertyGroupUnknown() {
        super(PropertyGroupUnknownHelper.id());
    }
}
