//
// Java code automatically generated by the JART IDL Compiler
// Do not edit this code!
//
// This Holder class is generated to allow support for out and inout
// parameter passing modes

package org.omg.CosActivity;
public final class SignalSetActiveHolder
    implements org.omg.CORBA.portable.Streamable
{
    public org.omg.CosActivity.SignalSetActive value;

    public SignalSetActiveHolder() {}

    public SignalSetActiveHolder(
        org.omg.CosActivity.SignalSetActive value
    )
    {
        this.value = value;
    }

    public void _read(
        org.omg.CORBA.portable.InputStream _stream
    )
    {
        value = org.omg.CosActivity.SignalSetActiveHelper.read(_stream);
    }

    public void _write(
        org.omg.CORBA.portable.OutputStream _stream
    )
    {
        org.omg.CosActivity.SignalSetActiveHelper.write(_stream, value);
    }

    public org.omg.CORBA.TypeCode _type()
    {
        return org.omg.CosActivity.SignalSetActiveHelper.type();
    }

}
