//
// Java code automatically generated by the Orbix 2000 IDL Compiler
// Do not edit this code!
//

package org.omg.CosActivity;

public interface SubordinateSignalSet
    extends SubordinateSignalSetOperations,
    org.omg.CosActivity.SignalSet
{
}
