/*
 * Automatically Generated by:
 * Arjuna Stub Generator Version 6.0.0 - $Date: 1997/06/11 20:25:11 $
 *
 * Do Not Edit By Hand
 */

#ifdef STUB
#  pragma @NoRename
#endif

#include "BufferCheck_stub.h"
int main ( int argc, char **argv )
{
ServerA oneAServer;

oneAServer.serve(argc, argv);
return 0;
}
