/*
 * Automatically Generated by:
 * Arjuna Stub Generator Version 6.0.0 - $Date: 1997/06/11 20:25:11 $
 *
 * Do Not Edit By Hand
 */

#ifdef STUB
#  pragma @NoRename
#endif

#ifndef STUB
#include <StubGen/RpcBuffer.h>
#include <StubGen/ClientRpcMan.h>


#ifndef BUFFERCHECK_SERVER
#undef BufferCheck
#define BufferCheck RemoteBufferCheck
#endif

class RemoteBufferCheck: public RemoteA
{
public:
	RemoteBufferCheck ( int& , int& , ClientRpcManager *_cRpcMan_ = ClientRpcManager::createInstance("BufferCheck",1));
	~RemoteBufferCheck ( );
	int Test ( Buffer , Buffer& );

protected:
	RemoteBufferCheck (const ClientRpcManager&, const RpcBuffer&);

private:
	ClientRpcManager _clientManager;
	RpcBuffer _myHashVal;
};


#ifdef BUFFERCHECK_SERVER
#undef BufferCheck
#define BufferCheck LocalBufferCheck
#endif

class LocalBufferCheck;

class ServerBufferCheck: public ServerA
{
public:
	ServerBufferCheck ();
	~ServerBufferCheck ();

	void serve (int, char **);
	Int32 dispatchToClass (LocalBufferCheck*, Int32, RpcBuffer&, RpcBuffer&);

private:
	Int32 dispatchToOper (LocalBufferCheck *,Int32, RpcBuffer&, RpcBuffer&);

	Int32 BufferCheck258928217 (LocalBufferCheck *, RpcBuffer&, RpcBuffer&);
	Int32 BufferCheck84735718 (LocalBufferCheck *, RpcBuffer&, RpcBuffer&);
	Int32 Test96138770 (LocalBufferCheck *, RpcBuffer&, RpcBuffer&);

	LocalBufferCheck *theRealObject;
	RpcBuffer _constructArgs_;
	Int32 _constructOpcode_;
	Int32 _constructRefCount_;
	RpcBuffer _constructResult_;
};
#endif


#ifdef STUB
#  define LocalBufferCheck BufferCheck
#endif

/* @Remote, @NoMarshall */ class LocalBufferCheck: public LocalA
{
public:
	/* @NoMarshall */ LocalBufferCheck ( int& , int& );
	/* @NoMarshall */ ~LocalBufferCheck ( );
	/* @NoMarshall */ int Test ( Buffer , Buffer& );
};

