#
# Copyright 1990, 1991,
# Computing Laboratory, University of Newcastle upon Tyne, UK.
#
# Permission to use, copy, modify and distribute this program for
# evaluation, teaching and/or research purposes only and without fee is
# hereby granted, providing that this copyright and permission notice
# appear on all copies and supporting documentation, and that similar
# conditions are imposed on any individual or organization to whom the
# program is distributed. The University of Newcastle upon Tyne makes no
# representation about the suitability of this software for any purpose.
# It is provided "as is" without express or implied warranty.
#

#
# $Id: Makefile,v 1.2 1991/08/19 19:48:16 nsmw Exp $
#
# "RPC" header makefile
#

MAKE = make

CC = cc
C++ = g++

CPPFLAGS =
CFLAGS =
C++FLAGS =
LDFLAGS =

MDEPFLAGS =

HEADERS = Manager.h \
          ClientManager.h \
          ServerManager.h \
          ClientRPC.h \
          ServerRPC.h

all:

tidy:
	rm -f core *~ \#*\# *.bak *.BAK

clean: tidy
	rm -f *.o

purge: clean

install:

depend:
