#!/bin/sh

if test "'x$JTSARJUNA_HOME'" = "'x'"
then
    echo Environment variable JTSARJUNA_HOME is not set.
else
    java -DPROPERTIES_FILE=$JTSARJUNA_HOME/etc/Arjuna.properties -DOBJECTSTORE_DIR=$JTSARJUNA_HOME/ObjectStore GridClient
fi
